### ISSUE TITLE
Test report fixes

### ISSUE THREAD

**Issue by wilpola** [wilpola/product-development-2022#10]
### Purpose
- This issue is meant to handle the issues reported in the test report from group P2

### Tasks
- [x]  Change version number
- [x] Look into IndexError Line 491
- [x] Fix UI blinking
- [x] Fix audio bug
- [x] Fix text blitting on top of itself in the workout view

**Comment by wilpola** [comment]
everything done
