### ISSUE TITLE
Web-app

### ISSUE THREAD

**Issue by wilpola** [wilpola/product-development-2022#13]
### Purpose
- The Flowga application needs a web-app that supports downloads for the python version, as well as a web based version of the application itself. 

### Tasks
- [x] Create boilerplate
- [x] Create landing view
    - [ ] ~~Make a button for downloading the app itself~~
    - [x] Make a button to to learn more (documentation)
- [x] Responsive site
- [ ] Web-app with same functions as before
- [ ] App Dashboard
    - [ ] Support stats
    - [ ] Start a workout
