### ISSUE TITLE
Add: Settings

### ISSUE THREAD

**Issue by wilpola** [wilpola/product-development-2022#7]
### Settings
At the current state, the application does not have a way to change volume, resolution or anything else. The purpose of the settings menu, or settings sequence, is to allow the user to change different things in the application.

### Execution
The way settings will be implemented into the application is simple. There will be different screens, with different functional components in them. What this means, is that the screen will receive its own Surface, that will be placed in the view, that the user can interact with. In terms of settings, there will be a settings file where all the changes will be written to, when the user clicks save. 

There has to be a sequence that gets fired if there are standing changes in the file, and the user is about to leave the settings sequence without saving. 

### TODO:

- [x] Create the file structure
- [x] Design the settings menu
- [x] #8
- [x] Trigger the settings sequence when it is selected from the main menu or pause menu
